security:
    firewalls:
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
        secured_area:
            pattern:    ^/
            form_login:
                login_path:  /login
                check_path:  /login/check
                default_target_path: /
            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }

    providers:
        main:
            entity:
                class:  Portfolio\CoreBundle\Entity\User
                property: username
                
    role_hierarchy:
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN]

    encoders:
        Portfolio\CoreBundle\Entity\User:
            algorithm:          sha1
            encode_as_base64:   false
            iterations:         1
